source "https://rubygems.org"

ruby "2.5.0"

gem "sinatra", require: "sinatra/base"

gem "activesupport", require: "active_support/all"
gem "dotenv"
gem "puma"
gem "require_all"

group :development do
end

group :development, :test do
  gem "better_errors"
  gem "binding_of_caller"
  gem "pry"
  gem "rerun"
end

group :test do
end

group :production do
end
